// <auto-generated />
using System;
using Games.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Games.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260728014537_AddPlatformTable")]
    partial class AddPlatformTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformsId")
                        .HasColumnType("int");

                    b.HasKey("GamesId", "PlatformsId");

                    b.HasIndex("PlatformsId");

                    b.ToTable("GamePlatform");
                });

            modelBuilder.Entity("Games.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "MMO"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Name = "Educational"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Name = "Party"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Name = "Board"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Name = "Card"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            Name = "Battle Royale"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 21,
                            Name = "MOBA"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 22,
                            Name = "RTS"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 23,
                            Name = "TBS"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 24,
                            Name = "Rhythm"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 25,
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 26,
                            Name = "Open World"
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 27,
                            Name = "Metroidvania"
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 28,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 29,
                            Name = "Tower Defense"
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 30,
                            Name = "Visual Novel"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 31,
                            Name = "Idle"
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 32,
                            Name = "Clicker"
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 33,
                            Name = "Incremental"
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 34,
                            Name = "Tycoon"
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 35,
                            Name = "City Builder"
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 36,
                            Name = "Life Sim"
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 37,
                            Name = "Dating Sim"
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 38,
                            Name = "Dungeon Crawler"
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 39,
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 40,
                            Name = "Roguelite"
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 41,
                            Name = "Tactical RPG"
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 42,
                            Name = "JRPG"
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 43,
                            Name = "ARPG"
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 44,
                            Name = "CRPG"
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 45,
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 46,
                            Name = "Action-Adventure"
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 47,
                            Name = "Sandbox Survival"
                        });
                });

            modelBuilder.Entity("Games.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("PriceABGames")
                        .HasColumnType("float");

                    b.Property<double>("PriceAmazon")
                        .HasColumnType("float");

                    b.Property<double>("PriceWalmart")
                        .HasColumnType("float");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Description Grand Theft Auto V",
                            ImageUrl = "",
                            ListPrice = 22.0,
                            PriceABGames = 16.0,
                            PriceAmazon = 19.0,
                            PriceWalmart = 20.0,
                            Producer = "Producteur GTA V",
                            Title = "GTA V"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Description FIFA 21",
                            ImageUrl = "",
                            ListPrice = 22.0,
                            PriceABGames = 16.0,
                            PriceAmazon = 19.0,
                            PriceWalmart = 20.0,
                            Producer = "Producteur FIFA 21",
                            Title = "FIFA 21"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Description Call of Duty",
                            ImageUrl = "",
                            ListPrice = 22.0,
                            PriceABGames = 16.0,
                            PriceAmazon = 19.0,
                            PriceWalmart = 20.0,
                            Producer = "Producteur Call of Duty",
                            Title = "Call of Duty"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Description Assassin's Creed",
                            ImageUrl = "",
                            ListPrice = 22.0,
                            PriceABGames = 16.0,
                            PriceAmazon = 19.0,
                            PriceWalmart = 20.0,
                            Producer = "Producteur Assassin's Creed",
                            Title = "Assassin's Creed"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Description Minecraft",
                            ImageUrl = "",
                            ListPrice = 22.0,
                            PriceABGames = 16.0,
                            PriceAmazon = 19.0,
                            PriceWalmart = 20.0,
                            Producer = "Producteur Minecraft",
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Description Fortnite",
                            ImageUrl = "",
                            ListPrice = 22.0,
                            PriceABGames = 16.0,
                            PriceAmazon = 19.0,
                            PriceWalmart = 20.0,
                            Producer = "Producteur Fortnite",
                            Title = "Fortnite"
                        });
                });

            modelBuilder.Entity("Games.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Games.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.HasOne("Games.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Games.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Games.Models.Game", b =>
                {
                    b.HasOne("Games.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
