// <auto-generated />
using GamesWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241202203838_PopulationCateroriesTable")]
    partial class PopulationCateroriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamesWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "MMO"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Name = "Educational"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Name = "Party"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Name = "Board"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Name = "Card"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            Name = "Battle Royale"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 21,
                            Name = "MOBA"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 22,
                            Name = "RTS"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 23,
                            Name = "TBS"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 24,
                            Name = "Rhythm"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 25,
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 26,
                            Name = "Open World"
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 27,
                            Name = "Metroidvania"
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 28,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 29,
                            Name = "Tower Defense"
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 30,
                            Name = "Visual Novel"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 31,
                            Name = "Idle"
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 32,
                            Name = "Clicker"
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 33,
                            Name = "Incremental"
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 34,
                            Name = "Tycoon"
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 35,
                            Name = "City Builder"
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 36,
                            Name = "Life Sim"
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 37,
                            Name = "Dating Sim"
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 38,
                            Name = "Dungeon Crawler"
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 39,
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 40,
                            Name = "Roguelite"
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 41,
                            Name = "Tactical RPG"
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 42,
                            Name = "JRPG"
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 43,
                            Name = "ARPG"
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 44,
                            Name = "CRPG"
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 45,
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 46,
                            Name = "Action-Adventure"
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 47,
                            Name = "Sandbox Survival"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
